Some improvements
pmem/run_qemu pull request #49
Opened 2024-06-26 15:13 UTC by miguelinux

These are some improvements to run_qemu.sh

2024-07-02 18:28 UTC, stellarhopper requested changes
Just a typo in the commit message subject - build_kernel instead of buil_kernel. Otherwise looks good.

2024-07-02 18:34 UTC, stellarhopper commented on run_qemu.sh
> +		sudo rm -f /usr/lib/modules/$kver
This feels a little bit risky..
Does mkinitramfs require this stuff to be in the host's /boot, /lib/modules etc?
If $kver is ever empty, these rm -rf can be disastrous for the host system.
Is it possible to not touch the host's /boot and /lib/modules at all?

2024-07-02 18:35 UTC, stellarhopper commented on run_qemu.sh
> +		sudo rm -f /usr/lib/modules/$kver
There's also a concern that if someone builds a kernel where kver is exactly the running `uname -r`, this would bork their system pretty badly.

2024-07-02 18:39 UTC, stellarhopper commented
Apart from the above comments, everything else looks good. Thanks for these updates @miguelinux

2024-07-04 17:23 UTC, miguelinux commented on run_qemu.sh
> +		sudo rm -f /usr/lib/modules/$kver
I'll remove this commit to improve it, and do another PR with it.

2024-07-04 17:23 UTC, miguelinux commented on run_qemu.sh
> +		install_mod_strip="INSTALL_MOD_STRIP=1"
Ok

2024-07-04 17:24 UTC, miguelinux commented
> Just a typo in the commit message subject - build_kernel instead of buil_kernel. Otherwise looks good.

Done

2024-07-09 00:57 UTC, merged