Adds Ubuntu support
pmem/run_qemu pull request #7
Opened 2022-01-21 22:18 UTC by ghost2490

2022-01-21 22:45 UTC, stellarhopper requested changes

2022-01-21 22:45 UTC, stellarhopper commented on ubuntu_rootfs.sh
> +apt_proxy=/etc/apt/apt.conf.d/00proxy
I suspect the 00proxy file name might be specific to your machine - is that right? Would it be worth it to instead copy everything in apt.conf.d/ over to the guest?

2022-01-21 22:45 UTC, stellarhopper commented on ubuntu_rootfs.sh
> +# Copyright (C) 2021 Intel Corporation. All rights reserved.
2022

2022-01-21 22:45 UTC, stellarhopper commented on run_qemu.sh
> +: "${my_tools:=$(readlink -f ~/git/my_tools)}"
lets drop the my_tools bits from this PR. It is nto related to Ubuntu support, and I have an idea for this - we already copy something like ~/git/extra-scripts, I'll make that a generic copy of that directory, and that will serve the same purpose as this, just with a different name.

2022-01-21 22:45 UTC, stellarhopper commented on run_qemu.sh
> +rootfssize="12G"
Was 12G necessary - did 10G work? It might be enough motivation to have a set of default rootfs sizes per distro - I'd hope to avoid a 50% increase in the image sizes.

2022-01-21 23:34 UTC, ghost2490 commented on ubuntu_rootfs.sh
> +apt_proxy=/etc/apt/apt.conf.d/00proxy
> Yes `00proxy` is likely to be specific to my machine. I'll remove the `00proxy`.

2022-01-21 23:35 UTC, ghost2490 commented on run_qemu.sh
> +rootfssize="12G"
Let me give 10G a try.

2022-01-21 23:36 UTC, ghost2490 commented on run_qemu.sh
> +: "${my_tools:=$(readlink -f ~/git/my_tools)}"
Got it

2022-01-21 23:37 UTC, ghost2490 commented on ubuntu_rootfs.sh
> +# Copyright (C) 2021 Intel Corporation. All rights reserved.
Done.

2022-01-21 23:41 UTC, ghost2490 commented on run_qemu.sh
> +: "${my_tools:=$(readlink -f ~/git/my_tools)}"
Done.

2022-01-22 00:24 UTC, ghost2490 commented on ubuntu_rootfs.sh
> +apt_proxy=/etc/apt/apt.conf.d/00proxy
Done.

2022-01-22 00:25 UTC, ghost2490 commented on run_qemu.sh
> +rootfssize="12G"
Works with 10 GB (`/dev/sda2       9.8G  9.4G     0 100% /`)

2022-01-24 18:22 UTC, merged

2022-01-24 18:22 UTC, stellarhopper commented
Looks good, thanks for adding this!